// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGXhKQybd17PUL9UFr_xsaLFVgQfNsJ4U',
    appId: '1:144766260592:web:95f9834afbce84d6a4ebb5',
    messagingSenderId: '144766260592',
    projectId: 'smmic-project',
    authDomain: 'smmic-project.firebaseapp.com',
    storageBucket: 'smmic-project.firebasestorage.app',
    measurementId: 'G-PF07EC7EJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVGtDjXmF-rtYGOe_Lg4ZQGrVNktLJHo',
    appId: '1:144766260592:android:318c745b4c89d0dea4ebb5',
    messagingSenderId: '144766260592',
    projectId: 'smmic-project',
    storageBucket: 'smmic-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4ofa97rx3fYn-q4LdHTiA7I_mg9A_0Qk',
    appId: '1:144766260592:ios:1b490165f65591aca4ebb5',
    messagingSenderId: '144766260592',
    projectId: 'smmic-project',
    storageBucket: 'smmic-project.firebasestorage.app',
    iosBundleId: 'com.example.smmic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4ofa97rx3fYn-q4LdHTiA7I_mg9A_0Qk',
    appId: '1:144766260592:ios:1b490165f65591aca4ebb5',
    messagingSenderId: '144766260592',
    projectId: 'smmic-project',
    storageBucket: 'smmic-project.firebasestorage.app',
    iosBundleId: 'com.example.smmic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGXhKQybd17PUL9UFr_xsaLFVgQfNsJ4U',
    appId: '1:144766260592:web:3bb8a6c1eb6f6e7ca4ebb5',
    messagingSenderId: '144766260592',
    projectId: 'smmic-project',
    authDomain: 'smmic-project.firebaseapp.com',
    storageBucket: 'smmic-project.firebasestorage.app',
    measurementId: 'G-9YLT4JN5H9',
  );
}
